[package]
name = "advent-of-code"
authors = ["Oliver Fleckenstein <oliverfl@live.dk>"]
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["blocking"] }
itertools = { version = "0.10.3" }
serde = { version = "1.0.144" }
serde_json = { version = "1.0" }
regex = "1.6.0"
hashbag = { version = "0.1.9" }
colored = { version = "2.0.0" }
