[package]
name = "advent-of-code"
authors = ["Oliver Fleckenstein <oliverfl@live.dk>"]
version = "0.1.0"
edition = "2021"

[dependencies]
advent-of-code-ocr = { path = "./advent-of-code-ocr" }
reqwest = { version = "0.11.11", features = ["blocking"] }
itertools = "0.12.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = { version = "1.0" }
regex = "1.6.0"
hashbag = { version = "0.1.9" }
colored = { version = "2.0.0" }
clap = { version = "4.0.29", features = ["derive"] }
csv = "1.1.6"
array2d = "^0.3.0"
string-builder = "0.2.0"
priority-queue = "1.3.0"
lazy_static = "1.4.0"
pathfinding = "4.1.1"
